# Generated by Django 5.2.4 on 2025-07-25 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount in dollars', max_digits=10)),
                ('category', models.CharField(help_text='Spending category (e.g., gaming, food, utilities)', max_length=100)),
                ('merchant', models.CharField(help_text='Store or service where transaction occurred', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional notes about the transaction', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the transaction was recorded')),
                ('transaction_date', models.DateTimeField(help_text='When the transaction actually occurred')),
                ('is_recurring', models.BooleanField(default=False, help_text='Whether this is a recurring transaction')),
                ('user', models.ForeignKey(help_text='User who made this transaction', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
