version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: megistus_user
      POSTGRES_PASSWORD: securepassword  # Change this!
      POSTGRES_DB: megistus_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgres://megistus_user:securepassword@db:5432/megistus_db
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  postgres_data: 